# Generated by Django 4.1.5 on 2023-01-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=300, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=300, null=True)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('total_quantity', models.IntegerField(blank=True, max_length=300, null=True)),
                ('date_shipped', models.DateTimeField(auto_now_add=True)),
                ('item_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
