# Generated by Django 4.1.5 on 2023-01-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_aisle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisle',
            name='title',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='total_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
