# Generated by Django 4.1.5 on 2023-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_aisle_title_alter_category_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_shipped',
        ),
        migrations.AlterField(
            model_name='aisle',
            name='title',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
