# Generated by Django 4.1.5 on 2023-01-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
