# Generated by Django 4.1.5 on 2023-01-23 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_shipping_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='aisle',
        ),
        migrations.DeleteModel(
            name='Aisle',
        ),
    ]
