# Generated by Django 4.1.5 on 2023-01-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_category_aisle_delete_aisle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shipping',
            new_name='Shipment',
        ),
    ]
