# Generated by Django 4.1.5 on 2023-01-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_sent_to_shipment_attn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='total_quantity',
            new_name='amount_received',
        ),
    ]
