# Generated by Django 4.1.5 on 2023-01-26 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_total_quantity_item_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='amount',
            new_name='amount_received',
        ),
    ]
